-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model analytics_stocks_cleaned filters required NULL rows.

{{ config(alias='analytics_stocks_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='analytics_stocks', tags=['staging_cleaned']) }}

select *
from {{ ref('v_analytics_stocks_for_cleaned') }}
