-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model analytics_sales_funnel_cleaned filters required NULL rows.

{{ config(alias='analytics_sales_funnel_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='analytics_sales_funnel', tags=['staging_cleaned']) }}

select *
from {{ ref('v_analytics_sales_funnel_for_cleaned') }}
