-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model tariffs_acceptance_cleaned filters required NULL rows.

{{ config(alias='tariffs_acceptance_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='tariffs_acceptance', tags=['staging_cleaned']) }}

select *
from {{ ref('v_tariffs_acceptance_for_cleaned') }}
