-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model tariffs_commission_cleaned filters required NULL rows.

{{ config(alias='tariffs_commission_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='tariffs_commission', tags=['staging_cleaned']) }}

select *
from {{ ref('v_tariffs_commission_for_cleaned') }}
