-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model finance_balance_cleaned filters required NULL rows.

{{ config(alias='finance_balance_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='finance_balance', tags=['staging_cleaned']) }}

select *
from {{ ref('v_finance_balance_for_cleaned') }}
