-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model finance_sales_reports_detailed_cleaned filters required NULL rows.

{{ config(alias='finance_sales_reports_detailed_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='finance_sales_reports_detailed', tags=['staging_cleaned']) }}

select *
from {{ ref('v_finance_sales_reports_detailed_for_cleaned') }}
