-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model fbw_supplies_cleaned filters required NULL rows.

{{ config(alias='fbw_supplies_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='fbw_supplies', tags=['staging_cleaned']) }}

select *
from {{ ref('v_fbw_supplies_for_cleaned') }}
