-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model communications_feedbacks_cleaned filters required NULL rows.

{{ config(alias='communications_feedbacks_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='communications_feedbacks', tags=['staging_cleaned']) }}

select *
from {{ ref('v_communications_feedbacks_for_cleaned') }}
