-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model communications_chats_cleaned filters required NULL rows.

{{ config(alias='communications_chats_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='communications_chats', tags=['staging_cleaned']) }}

select *
from {{ ref('v_communications_chats_for_cleaned') }}
