-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model orders_fbs_statuses_cleaned filters required NULL rows.

{{ config(alias='orders_fbs_statuses_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='orders_fbs_statuses', tags=['staging_cleaned']) }}

select *
from {{ ref('v_orders_fbs_statuses_for_cleaned') }}
