JSON_FILES = """
orders_fbs_new.json
orders_fbs_current.json
orders_fbs_archive.json
orders_fbs_statuses.json
orders_dbs_new.json
orders_dbs_completed.json
orders_dbs_statuses.json
orders_dbw_new.json
orders_dbw_completed.json
orders_dbw_statuses.json
orders_pickup_new.json
orders_pickup_statuses.json
items_cards.json
items_stocks.json
items_warehouses.json
finance_balance.json
finance_sales_reports.json
finance_sales_reports_detailed.json
report_orders.json
report_sales.json
tariffs_commission.json
tariffs_box.json
tariffs_acceptance.json
analytics_sales_funnel.json
analytics_stocks.json
promotion_campaigns.json
promotion_fullstats.json
communications_feedbacks.json
communications_chats.json
fbw_supplies.json
general_seller_info.json
""".strip().splitlines()
