-- generated by add_row_level_quarantine_wrappers.py
-- Row-level quarantine issues for required NULL fields in orders_cleaned.

{{ config(materialized='table') }}

select
    'orders_cleaned'::text as source_model,
    'chrt_id'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('orders_cleaned__all') }} src
where "chrt_id" is null

union all

select
    'orders_cleaned'::text as source_model,
    'nm_id'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('orders_cleaned__all') }} src
where "nm_id" is null

union all

select
    'orders_cleaned'::text as source_model,
    'rid'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('orders_cleaned__all') }} src
where "rid" is null
