-- generated by add_row_level_quarantine_wrappers.py
-- Row-level quarantine issues for required NULL fields in promotion_fullstats_cleaned.

{{ config(materialized='table') }}

select
    'promotion_fullstats_cleaned'::text as source_model,
    'app_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "app_index" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'dataset_name'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "dataset_name" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'day_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "day_index" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'nm_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "nm_index" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_app'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_app" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_day'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_day" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_nm'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_nm" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_payload_id'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_payload_id" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_record'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_record" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'raw_root'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "raw_root" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'record_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "record_index" is null

union all

select
    'promotion_fullstats_cleaned'::text as source_model,
    'root_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('promotion_fullstats_cleaned__all') }} src
where "root_index" is null
