-- generated by add_row_level_quarantine_wrappers.py
-- Row-level quarantine issues for required NULL fields in tariffs_acceptance_cleaned.

{{ config(materialized='table') }}

select
    'tariffs_acceptance_cleaned'::text as source_model,
    'dataset_name'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('tariffs_acceptance_cleaned__all') }} src
where "dataset_name" is null

union all

select
    'tariffs_acceptance_cleaned'::text as source_model,
    'raw_payload_id'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('tariffs_acceptance_cleaned__all') }} src
where "raw_payload_id" is null

union all

select
    'tariffs_acceptance_cleaned'::text as source_model,
    'raw_record'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('tariffs_acceptance_cleaned__all') }} src
where "raw_record" is null

union all

select
    'tariffs_acceptance_cleaned'::text as source_model,
    'record_index'::text as column_name,
    'required_null_after_normalization'::text as issue_code,
    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,
    to_jsonb(src) as row_payload,
    now()::timestamptz as detected_at
from {{ ref('tariffs_acceptance_cleaned__all') }} src
where "record_index" is null
