-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model report_sales_cleaned filters required NULL rows.

{{ config(alias='report_sales_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='report_sales', tags=['staging_cleaned']) }}

select *
from {{ ref('v_report_sales_for_cleaned') }}
