-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model report_orders_cleaned filters required NULL rows.

{{ config(alias='report_orders_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='report_orders', tags=['staging_cleaned']) }}

select *
from {{ ref('v_report_orders_for_cleaned') }}
