-- generated by add_row_level_quarantine_wrappers.py
-- Public staging_cleaned model. Only rows with required fields present pass further to core/marts.

select *
from {{ ref('communications_chats_cleaned__all') }}
where "dataset_name" is not null
  and "raw_payload_id" is not null
  and "raw_record" is not null
  and "record_index" is not null
