-- generated by infer_stock_products.py
-- Public products model includes inferred reference rows from stock_balances.

{{ config(materialized='table') }}

with base as (
    select * from {{ ref('products__base') }}
),
inferred as (
    select distinct on (sb."product_id")
        sb."client_id"::text as "client_id",
        sb."wb_account_id"::text as "wb_account_id",
        sb."product_id"::bigint as "product_id",
        sb."nm_id"::bigint as "nm_id",
        null::bigint as "nm_id_2",
        null::bigint as "imt_id",
        null::text as "nm_uuid",
        sb."vendor_code"::text as "vendor_code",
        sb."article"::text as "article",
        'Inferred product from stock balances ' || (sb."product_id")::text as "brand",
        null::bigint as "subject_id",
        null::text as "subject_name",
        null::text as "title",
        null::text as "description",
        null::jsonb as "photos",
        null::jsonb as "tags",
        null::text as "video",
        null::bigint as "dimensions_height",
        null::bigint as "dimensions_length",
        null::bigint as "dimensions_width",
        null::numeric as "dimensions_weight_brutto",
        false as "dimensions_is_valid",
        false as "kiz_marked",
        false as "need_kiz",
        false as "wholesale_enabled",
        null::numeric as "wholesale_quantum",
        now()::timestamp with time zone as "created_at",
        now()::timestamp with time zone as "updated_at",
        sb."source_system"::text as "source_system",
        sb."source_dataset"::text as "source_dataset",
        sb."source_row_id"::text as "source_row_id",
        sb."raw_payload_id"::bigint as "raw_payload_id",
        sb."record_index"::integer as "record_index",
        sb."source_loaded_at"::timestamp with time zone as "source_loaded_at",
        sb."core_loaded_at"::timestamp with time zone as "core_loaded_at"
    from {{ ref('stock_balances') }} sb
    where sb."product_id" is not null
      and not exists (
          select 1
          from base b
          where b."product_id" = sb."product_id"
      )
    order by sb."product_id"
)
select * from base
union all
select * from inferred
