-- generated by infer_stock_products.py
-- Public product_variants model includes inferred reference rows from stock_balances.

{{ config(materialized='table') }}

with base as (
    select * from {{ ref('product_variants__base') }}
),
inferred as (
    select distinct on (sb."product_variant_id")
        sb."client_id"::text as "client_id",
        sb."wb_account_id"::text as "wb_account_id",
        sb."product_variant_id"::bigint as "product_variant_id",
        sb."chrt_id"::bigint as "chrt_id",
        sb."product_id"::bigint as "product_id",
        sb."nm_id"::bigint as "nm_id",
        sb."vendor_code"::text as "vendor_code",
        sb."article"::text as "article",
        abs(('x' || substr(md5((sb."product_variant_id")::text), 1, 15))::bit(60)::bigint)::bigint as "barcode",
        sb."skus"::jsonb as "skus",
        null::jsonb as "characteristics",
        null::jsonb as "sizes",
        now()::timestamp with time zone as "created_at",
        now()::timestamp with time zone as "updated_at",
        sb."source_system"::text as "source_system",
        sb."source_dataset"::text as "source_dataset",
        sb."source_row_id"::text as "source_row_id",
        sb."raw_payload_id"::bigint as "raw_payload_id",
        sb."record_index"::integer as "record_index",
        sb."source_loaded_at"::timestamp with time zone as "source_loaded_at",
        sb."core_loaded_at"::timestamp with time zone as "core_loaded_at"
    from {{ ref('stock_balances') }} sb
    where sb."product_variant_id" is not null
      and not exists (
          select 1
          from base b
          where b."product_variant_id" = sb."product_variant_id"
      )
    order by sb."product_variant_id"
)
select * from base
union all
select * from inferred
