-- generated by add_row_level_quarantine_wrappers.py
-- Public staging_cleaned model. Only rows with required fields present pass further to core/marts.

select *
from {{ ref('orders_cleaned__all') }}
where "chrt_id" is not null
  and "nm_id" is not null
  and "rid" is not null
