{{ config(materialized='view', schema='quarantine') }}

select
    s.raw_payload_id,
    s.record_index,
    s.dataset_name,
    s.source_file,
    s.loaded_at,
    s.order_flow,
    s.order_kind,
    s.order_id,
    s.rid,
    s.order_uid,
    s.order_code,
    s.created_at,
    s.ddate,
    s.seller_date,
    s.delivery_type,
    s.pay_mode,
    s.article,
    s.nm_id,
    s.chrt_id,
    s.price,
    s.sale_price,
    s.final_price,
    s.converted_price,
    s.converted_final_price,
    s.currency_code,
    s.converted_currency_code,
    s.scan_price,
    s.warehouse_id,
    s.warehouse_address,
    s.office_id,
    s.supply_id,
    s.group_id,
    s.cargo_type,
    s.cross_border_type,
    s.color_code,
    s.comment,
    s.is_zero_order,
    s.is_b2b,
    s.is_archive,
    s.address_full,
    s.address_latitude,
    s.address_longitude,
    s.skus,
    s.raw_record,
    s.inserted_at,

    q.quality_status,
    q.quality_issues,
    q.warning_issues,
    q.issue_details,
    q.can_load_to_core,
    q.can_count_order,
    q.can_count_revenue,
    q.can_use_order_date,
    q.is_complete,

    s.source_system,
    s.source_url,
    s.file_hash,
    s.srid,
    s.barcode,
    s.delivery_method,
    s.delivery_service

from {{ ref('stg_orders_current') }} s
join {{ ref('orders_current_quality') }} q
  on q.raw_payload_id = s.raw_payload_id
 and q.record_index = s.record_index
where q.can_load_to_core = true
