{{ config(materialized='table', schema='core', alias='sales_funnel_metrics', tags=['core', 'core_analytics_promotion']) }}

with source as (

    select *
    from {{ ref('analytics_sales_funnel_cleaned') }}
    where can_load_to_cleaned = true

)

select
    client_id,
    wb_account_id,
    md5(concat_ws(
        '||',
        'sales_funnel_metric',
        raw_payload_id::text,
        record_index::text
    )) as sales_funnel_metric_key,

    loaded_at::date as metric_snapshot_date,
    loaded_at as metric_snapshot_at,

    product_nm_id as product_id,
    product_nm_id as nm_id,

    product_brand_name,
    product_feedback_rating,
    product_product_rating,
    product_stocks_balance_sum,
    product_stocks_mp,
    product_stocks_wb,
    product_subject_id,
    product_subject_name,
    product_tags,
    product_title,
    product_vendor_code,
    statistic_comparison_add_to_wishlist_dynamic,
    statistic_comparison_avg_orders_count_per_day_dynamic,
    statistic_comparison_avg_price_dynamic,
    statistic_comparison_buyout_count_dynamic,
    statistic_comparison_buyout_sum_dynamic,
    statistic_comparison_cancel_count_dynamic,
    statistic_comparison_cancel_sum_dynamic,
    statistic_comparison_cart_count_dynamic,
    statistic_comparison_conversions_add_to_cart_percent,
    statistic_comparison_conversions_buyout_percent,
    statistic_comparison_conversions_cart_to_order_percent,
    statistic_comparison_localization_percent_dynamic,
    statistic_comparison_open_count_dynamic,
    statistic_comparison_order_count_dynamic,
    statistic_comparison_order_sum_dynamic,
    statistic_comparison_share_order_percent_dynamic,
    statistic_comparison_time_to_ready_dynamic_days,
    statistic_comparison_time_to_ready_dynamic_hours,
    statistic_comparison_time_to_ready_dynamic_mins,
    statistic_comparison_wb_club_dynamic_avg_order_count_per_day,
    statistic_comparison_wb_club_dynamic_avg_price,
    statistic_comparison_wb_club_dynamic_buyout_count,
    statistic_comparison_wb_club_dynamic_buyout_percent,
    statistic_comparison_wb_club_dynamic_buyout_sum,
    statistic_comparison_wb_club_dynamic_cancel_count,
    statistic_comparison_wb_club_dynamic_cancel_sum,
    statistic_comparison_wb_club_dynamic_order_count,
    statistic_comparison_wb_club_dynamic_order_sum,
    statistic_past_add_to_wishlist,
    statistic_past_avg_orders_count_per_day,
    statistic_past_avg_price,
    statistic_past_buyout_count,
    statistic_past_buyout_sum,
    statistic_past_cancel_count,
    statistic_past_cancel_sum,
    statistic_past_cart_count,
    statistic_past_conversions_add_to_cart_percent,
    statistic_past_conversions_buyout_percent,
    statistic_past_conversions_cart_to_order_percent,
    statistic_past_localization_percent,
    statistic_past_open_count,
    statistic_past_order_count,
    statistic_past_order_sum,
    statistic_past_period_end,
    statistic_past_period_start,
    statistic_past_share_order_percent,
    statistic_past_time_to_ready_days,
    statistic_past_time_to_ready_hours,
    statistic_past_time_to_ready_mins,
    statistic_past_wb_club_avg_order_count_per_day,
    statistic_past_wb_club_avg_price,
    statistic_past_wb_club_buyout_count,
    statistic_past_wb_club_buyout_percent,
    statistic_past_wb_club_buyout_sum,
    statistic_past_wb_club_cancel_count,
    statistic_past_wb_club_cancel_sum,
    statistic_past_wb_club_order_count,
    statistic_past_wb_club_order_sum,
    statistic_selected_add_to_wishlist,
    statistic_selected_avg_orders_count_per_day,
    statistic_selected_avg_price,
    statistic_selected_buyout_count,
    statistic_selected_buyout_sum,
    statistic_selected_cancel_count,
    statistic_selected_cancel_sum,
    statistic_selected_cart_count,
    statistic_selected_conversions_add_to_cart_percent,
    statistic_selected_conversions_buyout_percent,
    statistic_selected_conversions_cart_to_order_percent,
    statistic_selected_localization_percent,
    statistic_selected_open_count,
    statistic_selected_order_count,
    statistic_selected_order_sum,
    statistic_selected_period_end,
    statistic_selected_period_start,
    statistic_selected_share_order_percent,
    statistic_selected_time_to_ready_days,
    statistic_selected_time_to_ready_hours,
    statistic_selected_time_to_ready_mins,
    statistic_selected_wb_club_avg_order_count_per_day,
    statistic_selected_wb_club_avg_price,
    statistic_selected_wb_club_buyout_count,
    statistic_selected_wb_club_buyout_percent,
    statistic_selected_wb_club_buyout_sum,
    statistic_selected_wb_club_cancel_count,
    statistic_selected_wb_club_cancel_sum,
    statistic_selected_wb_club_order_count,
    statistic_selected_wb_club_order_sum,

    source_system,
    dataset_name as source_dataset,
    md5(concat_ws('||', client_id, wb_account_id, raw_payload_id::text, record_index::text)) as source_row_id,
    raw_payload_id,
    record_index,
    loaded_at as source_loaded_at,
    now() as core_loaded_at

from source
