name: 'wb_dbt'
version: '1.0.0'
config-version: 2

profile: 'wb_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wb_dbt:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
    client_exports:
      +schema: client_demo
      +materialized: materialized_view


on-run-start:
  - "{{ ensure_safe_cast_functions() }}"
  - "{{ ensure_json_drift_policy_views() }}"
