-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model promotion_campaigns_cleaned filters required NULL rows.

{{ config(alias='promotion_campaigns_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='promotion_campaigns', tags=['staging_cleaned']) }}

select *
from {{ ref('v_promotion_campaigns_for_cleaned') }}
