-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model promotion_fullstats_cleaned filters required NULL rows.

{{ config(alias='promotion_fullstats_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='promotion_fullstats', tags=['staging_cleaned']) }}

select *
from {{ ref('v_promotion_fullstats_for_cleaned') }}
