from pathlib import Path
import json
import shutil
import sys
import time

ROOT = Path("/opt/wb_pipeline")
DBT = ROOT / "dbt" / "wb_dbt"
MANIFEST = DBT / "target" / "manifest.json"
GENERATED_LIST = ROOT / "tmp" / "row_quarantine_generated_files.txt"

MARKER = "generated by add_row_level_quarantine_wrappers.py"

def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'

def is_staging_cleaned_model(node: dict) -> bool:
    path = node.get("original_file_path") or node.get("path") or ""
    parts = Path(path).parts
    return "models" in parts and "staging_cleaned" in parts and path.endswith(".sql")

def get_model_file(node: dict) -> Path:
    original_file_path = node.get("original_file_path") or node.get("path")
    return DBT / original_file_path

def get_not_null_column(test_node: dict):
    if test_node.get("test_metadata", {}).get("name") != "not_null":
        return None

    if test_node.get("column_name"):
        return test_node["column_name"]

    kwargs = test_node.get("test_metadata", {}).get("kwargs") or {}
    if kwargs.get("column_name"):
        return kwargs["column_name"]

    return None

def main():
    if not MANIFEST.exists():
        print(f"[ERROR] manifest not found: {MANIFEST}")
        sys.exit(1)

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest.get("nodes", {})

    models = {
        uid: node
        for uid, node in nodes.items()
        if node.get("resource_type") == "model"
        and is_staging_cleaned_model(node)
        and not node.get("name", "").endswith("__all")
    }

    required_by_model = {uid: set() for uid in models}

    for uid, node in nodes.items():
        if node.get("resource_type") != "test":
            continue

        col = get_not_null_column(node)
        if not col:
            continue

        for dep_uid in node.get("depends_on", {}).get("nodes", []):
            if dep_uid in required_by_model:
                required_by_model[dep_uid].add(col)

    required_by_model = {
        uid: sorted(cols)
        for uid, cols in required_by_model.items()
        if cols
    }

    if not required_by_model:
        print("[WARN] no staging_cleaned models with not_null tests found")
        print("[WARN] nothing to wrap")
        return 0

    generated = []
    wrapped = []
    skipped = []

    issue_dir = DBT / "models" / "quarantine" / "row_quality"
    issue_dir.mkdir(parents=True, exist_ok=True)

    for uid, cols in sorted(required_by_model.items(), key=lambda x: models[x[0]].get("name", "")):
        node = models[uid]
        model_name = node["name"]
        model_path = get_model_file(node)

        if not model_path.exists():
            skipped.append((model_name, "model file not found"))
            continue

        original_sql = model_path.read_text(encoding="utf-8")

        if MARKER in original_sql and f"ref('{model_name}__all')" in original_sql:
            skipped.append((model_name, "already wrapped"))
            continue

        all_dir = model_path.parent / "_with_invalid_rows"
        all_dir.mkdir(parents=True, exist_ok=True)

        all_path = all_dir / f"{model_name}__all.sql"
        issue_path = issue_dir / f"rq_{model_name}_required_null_issues.sql"

        if all_path.exists() and MARKER not in all_path.read_text(encoding="utf-8", errors="ignore"):
            print(f"[ERROR] refusing to overwrite non-generated file: {all_path}")
            return 1

        if issue_path.exists() and MARKER not in issue_path.read_text(encoding="utf-8", errors="ignore"):
            print(f"[ERROR] refusing to overwrite non-generated file: {issue_path}")
            return 1

        shutil.move(str(model_path), str(all_path))

        all_sql = all_path.read_text(encoding="utf-8")
        all_path.write_text(
            f"-- {MARKER}\n"
            f"-- Original staging_cleaned model. Public model {model_name} filters required NULL rows.\n\n"
            f"{{{{ config(alias='{model_name}__all') }}}}\n\n"
            + all_sql,
            encoding="utf-8",
        )

        where_clause = "\n  and ".join(f"{qident(c)} is not null" for c in cols)

        wrapper_sql = (
            f"-- {MARKER}\n"
            f"-- Public staging_cleaned model. Only rows with required fields present pass further to core/marts.\n\n"
            f"select *\n"
            f"from {{{{ ref('{model_name}__all') }}}}\n"
            f"where {where_clause}\n"
        )

        model_path.write_text(wrapper_sql, encoding="utf-8")

        issue_selects = []

        for col in cols:
            issue_selects.append(
                "select\n"
                f"    '{model_name}'::text as source_model,\n"
                f"    '{col}'::text as column_name,\n"
                "    'required_null_after_normalization'::text as issue_code,\n"
                "    'Required field is NULL after staging_cleaned normalization. This can be caused by invalid_cast, missing field, or source NULL.'::text as issue_message,\n"
                "    to_jsonb(src) as row_payload,\n"
                "    now()::timestamptz as detected_at\n"
                f"from {{{{ ref('{model_name}__all') }}}} src\n"
                f"where {qident(col)} is null"
            )

        issue_sql = (
            f"-- {MARKER}\n"
            f"-- Row-level quarantine issues for required NULL fields in {model_name}.\n\n"
            "{{ config(materialized='table') }}\n\n"
            + "\n\nunion all\n\n".join(issue_selects)
            + "\n"
        )

        issue_path.write_text(issue_sql, encoding="utf-8")

        generated.extend([
            str(all_path.relative_to(ROOT)),
            str(model_path.relative_to(ROOT)),
            str(issue_path.relative_to(ROOT)),
        ])

        wrapped.append((model_name, cols))

    GENERATED_LIST.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_LIST.write_text("\n".join(generated) + "\n", encoding="utf-8")

    print("[OK] wrapped staging_cleaned models:")
    for model_name, cols in wrapped:
        print(f" - {model_name}: {', '.join(cols)}")

    if skipped:
        print("[WARN] skipped:")
        for model_name, reason in skipped:
            print(f" - {model_name}: {reason}")

    print(f"[OK] generated file list: {GENERATED_LIST}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
