-- generated by add_row_level_quarantine_wrappers.py
-- Public staging_cleaned model. Only rows with required fields present pass further to core/marts.

select *
from {{ ref('promotion_fullstats_cleaned__all') }}
where "app_index" is not null
  and "dataset_name" is not null
  and "day_index" is not null
  and "nm_index" is not null
  and "raw_app" is not null
  and "raw_day" is not null
  and "raw_nm" is not null
  and "raw_payload_id" is not null
  and "raw_record" is not null
  and "raw_root" is not null
  and "record_index" is not null
  and "root_index" is not null
