-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model general_seller_info_cleaned filters required NULL rows.

{{ config(alias='general_seller_info_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='general_seller_info', tags=['staging_cleaned']) }}

select *
from {{ ref('v_general_seller_info_for_cleaned') }}
