-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model items_stocks_cleaned filters required NULL rows.

{{ config(alias='items_stocks_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='items_stocks', tags=['staging_cleaned']) }}

select *
from {{ ref('v_items_stocks_for_cleaned') }}
