-- generated by add_row_level_quarantine_wrappers.py
-- Original staging_cleaned model. Public model items_warehouses_cleaned filters required NULL rows.

{{ config(alias='items_warehouses_cleaned__all') }}

{{ config(materialized='table', schema='staging_cleaned', alias='items_warehouses', tags=['staging_cleaned']) }}

select *
from {{ ref('v_items_warehouses_for_cleaned') }}
